### ISSUE TITLE
[Feature] skywalking-java agent optional-reporter-plugins by rocketmq 

### ISSUE THREAD

**Issue by chenyi19851209** [apache/skywalking#10248]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Considering the high efficiency of MQ transmission and the peak-elimination effect of MQ, our company (webank) uses the rocketmq client to report trace segment to the rocketmq broker, and develops a rockemq trace receiving plug-in based on the oap framework on the server side to receive trace information.
We want to contribute this feature to the skywalking community, will the community consider accepting it?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I am afraid this was contributed due to summer of code program.

https://github.com/SkyAPM/transporter-plugin-for-skywalking

It is lack of activities and feedback. 
According to history, the community onky accepted active feature in the ASF, and others could be maintained by yourself. If there are more end users are willing to use it, you could make the call whether contribute it to the upstream.

**Comment by chenyi19851209** [comment]
ok，got it. thanks
