### ISSUE TITLE
[Bug] Detection of existing license headers fails in 0.5.0

### ISSUE THREAD

**Issue by krassowski** [apache/skywalking#11302]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

License Tools (apache/skywalking-eyes)

### What happened

Once we updated `apache/skywalking-eyes/header` from v0.4.0 to v0.5.0 
typescript and CSS files using a different comment kind than default are no longer detected as having the license and thus incorrectly get a second copy of license header applied.

### What you expected to happen

I would expect the existing headers to be detected. I am struggling to see whether this is intended change in the release because it was unpublished (see https://github.com/apache/skywalking-eyes/pull/166#issuecomment-1680349992) and not published again (see https://github.com/apache/skywalking-eyes/releases - if there were release notes warning about breaking changes these are no longer visible)

### How to reproduce

This can be seen on https://github.com/jupyterlab/jupyterlab/pull/15068.

For example:

```diff
+ /*
+  * Copyright (c) Jupyter Development Team.
+  * Distributed under the terms of the Modified BSD License.
+  */
#!/usr/bin/env node
/* -----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/
```

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Hi @krassowski , thanks for reporting, this issue is brought by an enhancement in 0.5.0, https://github.com/apache/skywalking-eyes/pull/142 , now it strictly checks the `Copyright ...` header, and in your case, in 0.4.0, the `Copyright ...` line is stripped so it only checks the line `Distributed under the terms of the Modified BSD License` and it passed, now that the `Copyright ...` line is also checked, the `|` between `Copyright ...` line and `Distributed ...` line prevents the tests to pass, so I added `|` as a comment indicator in https://github.com/apache/skywalking-eyes/pull/168, hope it helps.

**Comment by kezhenxu94** [comment]
@krassowski and because 0.5.0 was just released not soon ago, I prefer you change the revision tag to the commit sha like 


```yaml
      - name: Fix License Header
        uses: apache/skywalking-eyes/header@a56e941983b9813919a4c665c095e2a9b8521ecb
        with:
          mode: fix
```

or if you want me to have a new release for 0.5.1, let me know.

**Comment by krassowski** [comment]
Thank you, that worked!
