### ISSUE TITLE
[Bug] skywalking-backend-js :: i use "mongoose": "^8.2.2", got error: Error installing plugin mongodb * /usr/src/app/node_modules/skywalking-backend-js/lib/core/PluginInstaller.js

### ISSUE THREAD

**Issue by liuqixing** [apache/skywalking#12038]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

NodeJS Server Side Agent (apache/skywalking-nodejs)

### What happened

i use "mongoose": "^8.2.2", got error, and can not access my mongodb any more
{
   message: 'Error installing plugin mongodb *',
   level: 'error',
   file: '/usr/src/app/node_modules/skywalking-backend-js/lib/core/PluginInstaller.js'
}

### What you expected to happen

can not access my mongodb any more

### How to reproduce

can not access my mongodb any more

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
```
{
message: 'Error installing plugin mongodb *',
level: 'error',
file: '/usr/src/app/node_modules/skywalking-backend-js/lib/core/PluginInstaller.js'
}
```

Failing to install `mongodb` plugin is harmless because you are using mongoose, and I can still get access to MongoDB via mongoose, please check your code whether works without skywalking.


I can successfully manipulate the MongoDB server with mongoose even the error occurs.

# Start MongoDB Server

```shell
docker run -it --rm -p 27017:27017 mongo:6
```

# Start SkyWalking OAP

```shell
docker run --name oap -p 11800:11800 apache/skywalking-oap-server:9.7.0
```

# Create npm project

```shell
mkdir repro && cd repro
cat <<EOF > package.json
{
  "name": "mongo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "node index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "mongoose": "^8.2.4",
    "skywalking-backend-js": "^0.7.0"
  }
}
EOF

cat <<EOF > index.js
const { default: agent } = require('skywalking-backend-js');
const mongoose = require('mongoose');

agent.start();

main().catch(err => console.log(err));

async function main() {
  await mongoose.connect('mongodb://127.0.0.1:27017/test');

  const kittySchema = new mongoose.Schema({
  name: String
});

  const Cat = mongoose.model('Cat', { name: String });

  const kitty = new Cat({ name: 'Zildjian' });
  kitty.save().then(() => console.log('meow'));
}
EOF
```


# Run the app

```shell
yarn run dev
```

And you'll see `meow` is printed, if you query the mongodb server directly `db.cats.find()`, you'll see the record is saved into mongodb.

If you want to report further issue, please, provide detailed reproducible steps like what you see above.
