### ISSUE TITLE
[Feature] Add Datadog java agent tracing support as a Zipkin trace input

### ISSUE THREAD

**Issue by peachisai** [apache/skywalking#12522]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Hi
I am enthusiastic about Datadog components, and  now I want to contribute a new feature that collects traces from the Datadog Java agent and converts them into Zipkin spans.
And I have a question.
Do I need to submit a SWIP?

### Use case

I have done it.
![BJF3C84AHL_6B3UON5EBB2](https://github.com/user-attachments/assets/526d5fb2-2140-43ed-acfd-cf383dcc4b6e)

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If you use dd agent, why don't you just use otel-collector to convert those traces?

**Comment by wu-sheng** [comment]
I don't want SkyWalking has to have various commercial protocol things, unless we have to.

But, otel ecosystem is there. We should use it well.

**Comment by peachisai** [comment]
> If you use dd agent, why don't you just use otel-collector to convert those traces?



> I don't want SkyWalking has to have various commercial protocol things, unless we have to.
> 
> But, otel ecosystem is there. We should use it well.

Well, otel is a little heavy, and I had read the codes ,It seems . Though DD is a commercial company, the `java agent` is follow 
the `Apache-2.0 protocal`.

**Comment by peachisai** [comment]
> I don't want SkyWalking has to have various commercial protocol things, unless we have to.
> 
> But, otel ecosystem is there. We should use it well.

Well, Otel is a bit heavy, and from the codes what I've seen , It doesn't seem to extrace the peer address from meta. Though DD is a commercial company, its java agent is follow the  `Apache-2.0 protocol`.

**Comment by peachisai** [comment]
> > I don't want SkyWalking has to have various commercial protocol things, unless we have to.
> > But, otel ecosystem is there. We should use it well.
> 
> Well, Otel is a bit heavy,I believe that providing direct support could be an advantage for Sw (maybe). And from the codes what I've seen , Otel doesn't seem to extract the peer address from meta, but Zipkin span has the  `remoteEndpoint` attribute .Though DD is a commercial company, its java agent is follow the `Apache-2.0 protocol`.

**Comment by wu-sheng** [comment]
I know they follow APLv2, and actually otel Java agent is a kind of dd agent fork.

I have concerns about this because what is actually use cases? What zipkin can't do, and zipkin support is a kind of alternative to zipkin community, which is getting colder and colder in activities. We don't have plan to support all protocols out thete.

Meanwhile, think dd agent can do otlp exporter itself? We supported that.

**Comment by wu-sheng** [comment]
Zipkin support is not our major feature. We don't compete with Zipkin after all.
SkyWalking protocol is unique to provide high performance topo analysis and APIs dependencies. I believe you know this.

So, brings more protocols to us could only increase the maintenance load. Otlp is the best we could support. And that is caused by we have otlp logs and metrics support before, and important for our ecosystem about server monitoring.

**Comment by peachisai** [comment]
> Zipkin support is not our major feature. We don't compete with Zipkin after all. SkyWalking protocol is unique to provide high performance topo analysis and APIs dependencies. I believe you know this.
> 
> So, brings more protocols to us could only increase the maintenance load. Otlp is the best we could support. And that is caused by we have otlp logs and metrics support before, and important for our ecosystem about server monitoring.

Ok, I understood.
