### ISSUE TITLE
How does skywalking work with webflux？

### ISSUE THREAD

**Issue by xiaoni157** [apache/skywalking#2925]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How does skywalking work with webflux？
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking ：6.1.0
ElasticSearch：6.3.2
webflux：5.0.8.RELEASE
- Which company or project?
Gateway
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

Webflux is nio and AsyncRestTemplate is nio. NullPointerException appears when threadLocal is used to obtain it. May I ask what has been done with spring-webflux_5.1.2.RELEASE? Do you have any plans to support other versions of webflux in the future?

![image](https://user-images.githubusercontent.com/24448049/59911537-bcf05780-9446-11e9-8ee5-1762b0307902.png)
![image](https://user-images.githubusercontent.com/24448049/59911566-cd083700-9446-11e9-9f76-ce5609f07c74.png)
![image](https://user-images.githubusercontent.com/24448049/59911582-d5607200-9446-11e9-91b2-7f53c55f3b6d.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Check our supported list, we have version supported list there in agent set up document.

**Comment by xiaoni157** [comment]
I know you don't support 5.0.8.RELEASE version now. Do you have plans to support other versions of webflux in the future?

**Comment by xiaoni157** [comment]
Or how do I need to modify it to support it

**Comment by wu-sheng** [comment]
> I know you don't support 5.0.8.RELEASE version now. Do you have plans to support other versions of webflux in the future?

Plugins developed and contributed for different frameworks and different versions, but it only comes from the community. Some contributors think one version is valuable to support, they could follow our development document, PR review, integration tests, in order to make it merged into the main repo. Like all these plugins you saw.
In SkyWalking, we are totally community-based and community-driven. So some new version supports require everyone like you to contribute.

But I found `spring-webflux_5.0.8.RELEASE-spring-mvc_5.0.8.RELEASE` in the test case, maybe there is some bugs, could you submit a new demo to help on reproducing this error?

**Comment by xiaoni157** [comment]
Ok, so what I'm going to do is rewrite the demo and reproduce the problem,I need some time. any other requirements?

**Comment by wu-sheng** [comment]
Just make us as easy as possible to make us run locally.

**Comment by wu-sheng** [comment]
No update in a month
