### ISSUE TITLE
default configuration of application.yml in docker image

### ISSUE THREAD

**Issue by innerpeacez** [apache/skywalking#3036]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
charts 6.1.0 and 6.2.0 image
Why do you build the default configuration of application.yml into the image rather than configure application.yml with using configmap.yaml?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
@hanahmily take a see.

**Comment by hanahmily** [comment]
There're serval reasons to provide embedded configuration files.

1. Simplify usage of docker image. User can start up a container with a few
of environment variables instead of a complicated application config file.

2. It is easier to release k8s and docker compose with a standalone docker
image. There's no need to sync config files between them.
