### ISSUE TITLE
为什么识别不了vert.x 项目？

### ISSUE THREAD

**Issue by jvmtar** [apache/skywalking#3046]
![image](https://user-images.githubusercontent.com/21865043/61033100-4e733980-a3f5-11e9-81eb-18d417120753.png)

**Comment by kezhenxu94** [comment]
English only in the community of an Apache project.

Just because the logo for vert.x did not show up? I think it does no harm as long as you got the correct traces, and if you really care, you can open a pull request to add the logo in the UI repo https://github.com/apache/skywalking-rocketbot-ui/tree/master/src/views/components/topology/assets

**Comment by jvmtar** [comment]
> 只在Apache项目社区中使用英语。
> 
> 只是因为vert.x的徽标没有出现？我认为只要你得到正确的痕迹就没有坏处，如果你真的在乎，你可以打开一个拉取请求，在UI回购中添加徽标[https://github.com/apache/skywalking-rocketbot-ui /树/主/ src目录/视图/组件/拓扑/资产](https://github.com/apache/skywalking-rocketbot-ui/tree/master/src/views/components/topology/assets)

Not just not identifying it,
Why is there no trace of gateway to vert.x?

**Comment by jvmtar** [comment]
> English only in the community of an Apache project.
> 
> Just because the logo for vert.x did not show up? I think it does no harm as long as you got the correct traces, and if you really care, you can open a pull request to add the logo in the UI repo https://github.com/apache/skywalking-rocketbot-ui/tree/master/src/views/components/topology/assets

Not just not identifying it,
Why is there no trace of gateway to vert.x?

**Comment by BFergerson** [comment]
As long as you're not using Vert.x with RxJava, https://github.com/apache/skywalking/pull/4840 will likely solve this issue.
