### ISSUE TITLE
Integration with micrometer?

### ISSUE THREAD

**Issue by 9n** [apache/skywalking#3053]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Micrometer provides good abstract for monitor, and spring boot 2 deeply integrate with micrometer.
I think its valuable for providing probe/integration with micrometer, but I can't find any information about this, Am I missing something?

**Comment by wu-sheng** [comment]
It is valuable or not, I don't know. But basically we are powered by language agents and mesh. If you could give us full proposal, we could discussion.

Right now, no one works on that, because agents are super powerful, we don't need others.

**Comment by krmeda** [comment]
I am interested in seeing micrometer support, because as an application developer I am interested in making custom metrics in one abstraction layer. For Spring Boot + Java language micrometer is giving me the flexibility to create metrics and then decide later at runtime where the metric needs to go or who it integrates to.

If Skywalking uses agents to gather information, then proposal would be to have an implementation of micrometer `MeterRegistry`[here](https://micrometer.io/docs/guide/customMeterRegistry) to plug into the existing skywalking metrics ingesting capabilities.  

That would allow for use cases where in development environment, i can bring up just my micro-service, and automated test my microservice is creating custom metric correctly using a prometheus exporter but in live environments, I turn on skywalking agent and have metrics stream.
