### ISSUE TITLE
skywalking6.1

### ISSUE THREAD

**Issue by moyuntiandi** [apache/skywalking#3138]
### Question
    skywalking6.1在配置elasticsearch集群的时候，只能配置一个es node的ip，但是es集群的多个node之间master是可能会变化的，所以如果要配置多个es node的ip,这个版本支持嘛

**Comment by kezhenxu94** [comment]
Please use English to open an issue next time because Apache SkyWalking is an international community, using English should be more friendly to others who don't speak Chinese and **you can get response more quickly** from them (if possible)

you can use multiple addresses with comma(`,`) separated in the config `SW_STORAGE_ES_CLUSTER_NODES`, such as `host1:9200,host2:9200`

**Comment by omegazeng** [comment]
helm chart repo can not file an issue, here: https://github.com/apache/skywalking-helm 

https://github.com/apache/skywalking-helm/blob/6fe5e6f0d3b7686c6be0457733e825ee68cb9b35/chart/skywalking/templates/_helpers.tpl#L139
https://github.com/apache/skywalking-helm/blob/6fe5e6f0d3b7686c6be0457733e825ee68cb9b35/chart/skywalking/templates/_helpers.tpl#L100

This chart does not support multiple es hosts. 
@kezhenxu94
