### ISSUE TITLE
APM Agent enhacements

### ISSUE THREAD

**Issue by itziklavon** [apache/skywalking#3179]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ X ] Feature or performance improvement

### Requirement or improvement
Hi, I would like to add the following plugins in order to be able to monitor better the Java application.
1) dropwizard plugin - we have some old services who use Dropwizard as framework, we would like to have some close integration as Spring application has
2) Hibernate plugin
3) MyBatis plugin
4) add total time spent queying DB(sql/mongo), currently there is only the prepare statement and the commit, it would be better if could get the whole time
5) same goes for external http request

and the last thing is still far ahead but it is something to think on
currently there is a big project in process - OpenTelemtry, which is merge between opentracing and opencensus, 2 of the largest tracing platforms, maybe think on a way to integrate with their agent as well, for better understanding of the  applicaiton perfomance.

willing to help in whatever i can(would need some reference though)

in general great project and great work!!!!

**Comment by wu-sheng** [comment]
For plugins, we are open to accept, take a ref to plugin development document.

For DB, whole access time is logically, it is different. I think more reasonable metrics are transaction time metrics, but it is not easy.

Speaking external http, it is shows in topo, just don't show endpoint level. It looks like a little too much payload to analysis and storage. Because at the agent perspective, there is not real external call.

OpenTelemetry, I would not be too optimistic. I am a member OpenTracing Specification Council for long time, that thing is not that good as it described. Due to we have auto instrumentation plugin, OpenTelemetry  and OpenTracing things should be treated as an manual instrument API in business codes only, but not in framework level. We have OpenTracing toolkit for that purpose. You could use it today.

**Comment by wu-sheng** [comment]
Plugin should be easy to start.

**Comment by itziklavon** [comment]
> For plugins, we are open to accept, take a ref to plugin development document.
> 
> For DB, whole access time is logically, it is different. I think more reasonable metrics are transaction time metrics, but it is not easy.
> 
> Speaking external http, it is shows in topo, just don't show endpoint level. It looks like a little too much payload to analysis and storage. Because at the agent perspective, there is not real external call.
> 
> OpenTelemetry, I would not be too optimistic. I am a member OpenTracing Specification Council for long time, that thing is not that good as it described. Due to we have auto instrumentation plugin, OpenTelemetry and OpenTracing things should be treated as an manual instrument API in business codes only, but not in framework level. We have OpenTracing toolkit for that purpose. You could use it today.

can we have opencensus toolkit as well?
or it is to big assignment

i will look on the documentation and will see how i can build plugins
thanks!

**Comment by wu-sheng** [comment]
Toolkit is also open to contribute, but build one takes time. Today, core committers at least are not working on this. I just even added bootstrap auto instrumentation. Most users, if they want codes level instrumentation, they choose skywalking annotation to target method.
