### ISSUE TITLE
Alarm results displayed in random order not in time series?

### ISSUE THREAD

**Issue by bowenliang123** [apache/skywalking#3233]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 6.2 on CentOS 7.6
with ElasticSearch6 as storage

- What happen?

Confused to see the Alarm results displayed in random order rather than in a stable order (descending or ascending) in time series.

![image](https://user-images.githubusercontent.com/1935105/62749114-c6349280-ba8d-11e9-9a5d-9541967f81d8.png)

___

**Comment by wu-sheng** [comment]
Should be time based desc order. Which storage are you using?

Are you interested to send a pull request to fix? This is an easy fix

**Comment by bowenliang123** [comment]
Using the ElasticSearch 6.5.4 as storage.
Sorry that I couldn't send a fix for you asI don't know the exact cause for this problem.

Maybe I should upgrade to the latest Skywalk 6.3.0 and try again.

**Comment by wu-sheng** [comment]
@JaredTan95 Could you recheck this? Including ElasticSearch and MySQL storage?

**Comment by bowenliang123** [comment]
upgraded to 6.3 and the problem still occurs.

**Comment by wu-sheng** [comment]
@bowenliang123 I never said this is fixed in 6.3. I said this needs to be fixed. This is an easy bug, just change query order condition.

**Comment by bowenliang123** [comment]
@wu-sheng keep calm , wu . i am just reporting the issue here in case you  want to figure it out in your latest public release. I don't think we could assume every user of SkyWalking could be a easy contributor for SkyWalking, which requires lots of skills and background. And as the kind users, we are doing the best for sumit the possible bug for this specific open source project. We are just trying to do the same great as what you genius contributors do. Thanks.

**Comment by wu-sheng** [comment]
@bowenliang123 Agree with you. At the same time, GitHub milestone is set when you asked. Open source project has to depend on contributors, that is the way it lives. I know, there are a lot of open source projects in China maintained by an individual or one single company. So, people could submit an issue and look forward to fixed in the short term.

But in SkyWalking, and many diverse communities in Apache, it is working in this way. Our so-called PMC team(core team) are all volunteers, they respond to their own agenda. They contribute the things they want, fix issues they think critical. 

You could see in many issues, I respond welcome to submit contributions/pull requests because that is the only way worked out. That is why SkyWalking could keep growing w/o a single company controlled. And only in those cases, the project could be better with time, even some core members are busy and leave the project, even I am busy in something else, someones like @kezhenxu94 @zhaoyuguang @peng-yongsheng could step in, work with the community and make progress.
