### ISSUE TITLE
alarm_record TTL

### ISSUE THREAD

**Issue by wuxingye** [apache/skywalking#3329]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

------

### Question

- What do you want to know?

ttl works wrong

------

### Bug

- Which version of SkyWalking, OS and JRE?

SkyWalking: 6.3

Elasticsearch:6.8.2

OS and JRE: official docker images

mode: Zookeeper cluster

- Which company or project?

Thomas Cook

- What happen?
  If possible, provide a way for reproducing the error. e.g. demo application, component version.

system running two days, and kill down last night;

when i start up it this morning,  just 20190825 data remaining, and 20190824 was deleted, such as alarm_record-20190825 and so on.

i wanna know, how ttl works.

my config is official default

------

### Requirement or improvement

- Please describe about your requirements or improvement suggestions.

how ttl works, version 6.3.0

especially, alarm_record

**Comment by wu-sheng** [comment]
In 6.3, there is a TTL bug, which have been fixed in master branch.  Take a look at this doc, https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/ttl.md#elasticsearch-6-storage-ttl.
Use minuteMetricsDataTTL, hourMetricsDataTTL and dayMetricsDataTTL to replace otherMetricsDataTTL. And Record TTL is not working, it uses dayMetricsDataTTL.
Ref #3283 #3292
