### ISSUE TITLE
how customize the name of mysql，the 3th part service

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3359]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
I would like to customize the names of these services, such as mysql, redis, mq 。。。
Is there any documentation about this？
<img width="418" alt="Snipaste_2019-08-28_11-38-26" src="https://user-images.githubusercontent.com/52440226/63824157-c3d8a080-c988-11e9-9ee2-408be747d447.png">

**Comment by wu-sheng** [comment]
There is no such mechanism about this.

**Comment by wu-sheng** [comment]
If you want, propose an issue about how to do it, we could discuss it on there.

**Comment by webb2019** [comment]
> If you want, propose an issue about how to do it, we could discuss it on there.

I found that for independently launched service programs, as long as the agent.service_name of agent.config is configured, the name displayed on skywalking UI can be configured, but when it comes to mysql, skywalking seems to automatically take the host name of datasource.url as the name.I'm just asking if there's a way like zipkin probe to put parameters in the url of mysql configuration,such as "?Servicename =mydbname" set custom name, displayed on skywaling's UI

**Comment by wu-sheng** [comment]
We are not asking change to the target application. What Zipkin did, it is Zipkin choice, I am asking that, if you want to SkyWalking supports the rename, you need to submit the why to implement, rather than a simple idea. No one is working or asked that before, you are the first. Unless you start taking actions, I am afraid you have to wait anyone wants to do that.
