### ISSUE TITLE
Is it necessary to add MQ (Kafka or RabbitMQ) in skywalking ?

### ISSUE THREAD

**Issue by stone-wlg** [apache/skywalking#3435]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- I would like to know, is it necessary to add MQ as below:
![image](https://user-images.githubusercontent.com/2622666/64482353-c9ed3d80-d222-11e9-92a8-5ebcba538c16.png)

**Comment by wu-sheng** [comment]
Let's talk about this, since a lot of people used to ask about this before.

There are two parts of questions related to MQ.
# Is MQ a good or right way to community with OAP backend?
This question comes out when people think about what happens when the OAP cluster is not powerful enough or offline. 
But I want to ask the questions before answer this.
1. Why do you think OAP should be not powerful enough? As it is not, the speed of data analysis wouldn't catch up with producers(agents). Then what is the point of adding new deployment requirement?
1. Maybe you will argue says, the payload is sometimes higher than usual as there is hot business time. But, my question is how much higher? 
1. If less than 40%, how many resources will you use for the new MQ cluster? How about moving them to new OAP and ES nodes?
1. If higher than 40%, 70%~2x? Then, I could say, your MQ wastes more resources than it saves. Your MQ would support 2x~3x payload, and with 10%-20% cost in general time. Furthermore, in this case, if the payload/throughput are so high, how long the OAP cluster could catch up. I would say never before it catches up, the next hot time event is coming.

Besides all this analysis, why do you want the traces still 100%, as you are costing so many resources? Better than this, we could consider adding a better dynamic trace sampling mechanism at the backend, when throughputs go over the threshold, active the sampling rate to 100%->10% step by step, which means you could get the OAP and ES 3 times more powerful than usual, just ignore the traces at hot time.

# How about MQ metrics data exporter?
I would say, it is already available there. Exporter module with gRPC default mechanism is there. It is easy to provide a new implementor of that module.

Here are my thoughts, hope it helps.

**Comment by wu-sheng** [comment]
@stone-wlg Any further question?

**Comment by stone-wlg** [comment]
> @stone-wlg Any further question?

No, thanks

**Comment by junneyang** [comment]
> Let's talk about this, since a lot of people used to ask about this before.
> 
> There are two parts of questions related to MQ.
> 
> # Is MQ a good or right way to community with OAP backend?
> This question comes out when people think about what happens when the OAP cluster is not powerful enough or offline.
> But I want to ask the questions before answer this.
> 
> 1. Why do you think OAP should be not powerful enough? As it is not, the speed of data analysis wouldn't catch up with producers(agents). Then what is the point of adding new deployment requirement?
> 2. Maybe you will argue says, the payload is sometimes higher than usual as there is hot business time. But, my question is how much higher?
> 3. If less than 40%, how many resources will you use for the new MQ cluster? How about moving them to new OAP and ES nodes?
> 4. If higher than 40%, 70%~2x? Then, I could say, your MQ wastes more resources than it saves. Your MQ would support 2x~3x payload, and with 10%-20% cost in general time. Furthermore, in this case, if the payload/throughput are so high, how long the OAP cluster could catch up. I would say never before it catches up, the next hot time event is coming.
> 
> Besides all this analysis, why do you want the traces still 100%, as you are costing so many resources? Better than this, we could consider adding a better dynamic trace sampling mechanism at the backend, when throughputs go over the threshold, active the sampling rate to 100%->10% step by step, which means you could get the OAP and ES 3 times more powerful than usual, just ignore the traces at hot time.
> 
> # How about MQ metrics data exporter?
> I would say, it is already available there. Exporter module with gRPC default mechanism is there. It is easy to provide a new implementor of that module.
> 
> Here are my thoughts, hope it helps.

一句话，不支持MQ，意味着整个平台是封闭的！

**Comment by wu-sheng** [comment]
@junneyang I think you totally misread the FAQ, and get a wrong conclusion. 

SkyWalking doesn't support MQ to report trace in official release, yes. But you could extend itby yourself. Many people have done this internally. But they didn't contribute back, as an open source community, We can't and shouldn't require them to do that.

So, for MQ, you can.
