### ISSUE TITLE
 What the sampling mechanism is

### ISSUE THREAD

**Issue by liyanyan-dev** [apache/skywalking#3482]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I want to know what the sampling mechanism is? For example, I have 3 services and are distributed in different nodes. The calling relationship is A->B->C. When I configure the sampling to 300, if a call A is acquired, B and C will be collected. Is it still possible that in a call chain, A and C are collected, B is discarded, and the actual call chain becomes A->C?
If this is the latter case, the configuration of the sample may cause the call chain displayed on the web interface to be missing or incorrect.

我想了解一下采样的机制是什么？例如我有3个服务，并且分布在不同的节点，调用关系为A->B->C；当我配置采样为300时，如果某一次调用A被采集，B和C一定会被采集？还是有可能在一次调用链中，A和C被采集到，B被丢弃，实际调用链就成了A->C?如果是后一种这样的话，配置采样之后就有可能导致在web界面显示的调用链缺失或者不正确

___
### Bug
- Which version of SkyWalking, OS and JRE?
 skywalking v6.20
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This wouldn't happen, if the trace segment has been sampled, then all upstream trace segments will be sampled automatically.

**Comment by ArvinDevel** [comment]
> This wouldn't happen, if the trace segment has been sampled, then all upstream trace segments will be sampled automatically.

1.What's the mechanism? Assume B was sampled firstly, how does A know that the B was sampled and then sample itself?
2.Does skywalking support tail-based sampling? Since tail-based sampling captures all outliers so that you don’t miss crucial trace data when you are troubleshooting a performance issue.

**Comment by wu-sheng** [comment]
1. I was saying upstream service, the context propagated, that is why upstream knows.
2. Tail sampling is not supported, because the cost has been made in the downstream, this wouldn't have much help. SkyWalking could easily support 100% sampling in the product env, and various sampling mechanism in the OAP server side. We can't see the real requirement for the tail sampling. And tail sampling is inevitable to fail when MQ or async involved, which would be quite confused for the users.
