### ISSUE TITLE
Support search by customize tag in trace page

### ISSUE THREAD

**Issue by o-oops** [apache/skywalking#3524]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Can Skywalking support search by tag in trace page?

**Comment by wu-sheng** [comment]
We don't support that. I will cause a lot of payload, most are unnecessary.

**Comment by liangxp** [comment]
@wu-sheng Has this task been added to the 6.5. X milestone? The existing schemes are to modify traceinstance, add tag storage, and store tag to traceid at the same level. Does the working group have a better plan?

**Comment by wu-sheng** [comment]
No, this is not a feature to be added.

**Comment by liangxp** [comment]
@wu-sheng As a skywalking developer, do you have any good suggestions on how to implement this function?

**Comment by wu-sheng** [comment]
If you want, could extend an index to save the tags and trace id, then query that index first and get all traces based on the results.

**Comment by Jedore** [comment]
@liangxp Can I ask your solution about this question?

**Comment by MaShizhen** [comment]
My understanding is that distributed tracing is automatically managed by the SkyWalking SDK, which relieves users of any additional handling. Currently, the log panel already supports content-based searching, which is quite satisfactory for our needs.

For frontend logs, we also require the ability to search by content. For instance, if a user reports encountering a white screen while using the app, we need the capability to search for logs related to that specific user in the log panel to facilitate issue localization.

However, due to the limitations of the current version of the frontend log panel's search functionality, our plan is to leverage the /v3/logs API to report frontend error logs. By doing so, these logs will be displayed in the backend log panel, effectively meeting our troubleshooting requirements. This approach ensures that we can effectively diagnose and address issues.
