### ISSUE TITLE
Make agent plugin tests in PR only necessary.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#3658]
Today, we have 3 agent test jobs, lead by @dmsolr and jenkins setup by @kezhenxu94. With many contributors' help, especially @arugal, over 1/3 cases have been moved in. 
Even today, we have a little issue about job-3, it should be fixed by INFRA in the short term. And we already got a sponsor(tetrate.io)'s VMs(4) and @x22x22's one, plugin tests are still heavy payload. 
We all agree that, these jobs are significantly important for the project, but they are not necessary in all PR cases. Such as backend change only(no protocol change), UI change and documentation changed.

We should invest one test optimization starting by plugin tests, if and only if the `apm-sniffer` and `apm-protocol`(submodule) has changes, plugin tests should be done, otherwise, we could do a quick success status set for all 3 jobs.

**Comment by wu-sheng** [comment]
There is one hard job in this, which is the submodule update check. So, we have to compare the file after `submodule update`, but exclude the `.gitsubmodule` file.

Let's work on a general shell to set the fast-success mechanism in the CI process. In this shell, we could set up compare folders and files, if all of those are unchanged, then we turn the job into fast success, even without compile requirement.

As a result, we should have
1.  e2e tests should run in source code changes or Jenkins control file changes.
1. plugin tests should run in agent and agent protocol changes or Jenkins control file changes.
1. CI should run in source code changes or Jenkins control file changes.
1. No CI, e2e and plugin tests should be run if only document changes.

All these should accelerate the speed of PR review, and make our VM usage for real good requirements.

**Comment by wu-sheng** [comment]
This is only a high priority work, but we should do it.

**Comment by kezhenxu94** [comment]
to track this task, we have several sub-tasks here:

- [x] submodule changes should trigger build if related
- [x] list the changed file sets to trigger/skip E2E, CI, Agent Test
- [ ] comment on PR when skipped

this is technically feasible, we can access the asf-git credential in Jenkins job (although just read access to this repo, but it's obviously enough to comment),

the difficulty is there may be multiple jobs skipped, say E2E, Agent-Test-Workload 1~3, and we just want only one comment here, avoiding flooding the timeline of pull request, but it's a **nice to have** feature, I'll try to bring the comment here, and later to optimize it (one comment)

- [ ] support manually trigger build job forcibly, in case that the condition failed to detect

this is the most time-waste sub-task here, after struggling nearly a whole day, it turns out that, jobs triggered by comment on PR is not different from that are triggered by push events, there is no something like `triggeredByUserId`

A possible workaround is to compare the current job with the previous job, if the two commit id is the same, meaning one commit is triggered more than one time (one of which is triggered manually), then build it forcibly.

Will try to do task 3 and task 4 soon if there is no bug in design above, need some review on the thought above, especially task 4 @wu-sheng

**Comment by wu-sheng** [comment]
I am still thinking forcely trigger is not that necessary. For comment, it is OK to have separated for now, or even no comment. That is not a complex rule, we have many PRs to verify in one or two weeka to make it trusted. 
So, feel free to skip these.

**Comment by kezhenxu94** [comment]
> I am still thinking forcely trigger is not that necessary. For comment, it is OK to have separated for now, or even no comment. That is not a complex rule, we have many PRs to verify in one or two weeka to make it trusted.
> So, feel free to skip these.

Then I think we could make the first version merged, and see the result for a while

**Comment by wu-sheng** [comment]
Good for me. I will review the PR tonight. I am back to Kyiv now.
