### ISSUE TITLE
Run for a period of time without data

### ISSUE THREAD

**Issue by wankaishun** [apache/skywalking#3893]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
 Why is there no data after running for some time
 
- What happen? 
![QQ截图20191119165305](https://user-images.githubusercontent.com/20121479/69131287-14294f80-0aed-11ea-950b-f5b6841e3cc9.png)
jdk:1.8
skywalking:6.1.0
es:6.1.0

**Comment by wu-sheng** [comment]
ES 6.3.2+ is required, we indicated it in the documents. Please follow. Check your server time/time zone, and ES configuration in documents. 

Also, provide logs and data in ES, otherwise, what do you expect to have from us? You are just giving us a screenshot showing nothing. Open source project requires you to invest the reason rather than asking.
