### ISSUE TITLE
is there an official test report about OAP clusters?

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4010]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Question or discussion

___
### Question
- What do you want to know?
i want to use skywalking in my company ,but i only find the offical test for java agent 

I want to know the aop system performance limit for all samples,
I want to know the consumption of aop cluster resources and the qps it bears,
And I also want to know the cost comparison between oap cluster and spark / message queue
I know this statement is not strict,
Specific test points:
Does the trace node have a size limit, and if it is relatively large, does it affect the performance of aop?
Aop qps bearer of each node under specific resource constraints
How much performance can be improved over spark + queue at the same resource cost

Can i join sw's qq group

**Comment by wu-sheng** [comment]
> I want to know the aop system performance limit for all samples,
> I want to know the consumption of aop cluster resources and the qps it bears,

First of all, aop should be `OAP`. You have this typo in all your questions.
I think this is nearly impossible to provide official test. These cost a lot of resources, as we don't have that in the Apache foundation. There are some blogs on official website, http://skywalking.apache.org/blog/, posted by some PMC members. But they are mostly service mesh scenarios.

More people are more interested about agent performance rather than backend.

> And I also want to know the cost comparison between oap cluster and spark / message queue
> I know this statement is not strict,
> Specific test points:
> Does the trace node have a size limit, and if it is relatively large, does it affect the performance of aop?
> Aop qps bearer of each node under specific resource constraints
> How much performance can be improved over spark + queue at the same resource cost

We don't use traditional data analysis tech, big data-related because we don't care actually. If you learn more about the SkyWalking tracing module and analysis logic, you will know what I am talking about. So for my understanding, you can do by using spark or anything, but no performance change.

> Can i join sw's qq group

If you want, they are open to anyone. But tech related discussions only should happen on GitHub, or preferred on SkyWalking mail list.
