### ISSUE TITLE
[e2e] MySQL e2e test could pass even MySQL driver downloaded failure.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#4343]
We detected a high priority e2e test issue at #4335, the download link of MySQL driver is dead, but the e2e test could pass every time.

This is a high priority test issue, which makes reviewers can't use the test to verify the codes. @kezhenxu94 please take this as the 1st priority thing to fix.

**Comment by wu-sheng** [comment]
The download link will be fixed through #4335, but we need to invest why and fix it ASAP.

**Comment by dmsolr** [comment]
@kezhenxu94 , if you don't have time, I can submit a PR to pre-install the driver in e2e-container image.

**Comment by wu-sheng** [comment]
@dmsolr The download link has been fixed, the issue is why the test passed when the download fails

**Comment by dmsolr** [comment]
got it.

**Comment by kezhenxu94** [comment]
The e2e still passed because the failure (download) stops the replacement of `application.yaml`, and it falls back to H2 storage, this is fixed by https://github.com/SkyAPMTest/e2e-container/commit/bf4cee3bd5488262a51b33d80fa2246f39ad019f and I just released e2e-container 1.5 https://hub.docker.com/r/skyapm/e2e-container/tags?page=1&ordering=last_updated since @dmsolr you're upgrading the container versions in your PR, please upgrade them to 1.5
