### ISSUE TITLE
SW data loss

### ISSUE THREAD

**Issue by huangpang** [apache/skywalking#4485]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug 
- [ ] Requirement
- [ ] Feature or performance improvement

___
- Which version of SkyWalking, OS and JRE?
   skywalking 6.5
   jre 1.8 
  centos 6
  es 6.5
- Which company or project?

- What happen?

I deployed skywalking in the development environment, which is a brand new environment

In the development process, I associate the traceid of skywalking with my own logs, and use apm-toolkit-trace，apm-toolkit-opentracing  class library
The code is as follows:
`TraceContext.traceId()`

Later, I found that some traceids could not find information in skywalking UI
For example, there are two adjacent requests (both paths are the same), time:
2020-03-10 15:54:55(30.81.15838268955460009)，2020-03-10 15:54:50(30.80.15838268908580009)

2020-03-10 15:54:55 The associated traceid (30.81.15838268955460009) can be used to query information in SW, while the other cannot

I observed the log of SW (skywalking-oap-server.log), which only contained info messages

This kind of situation happens a lot. I don't know if it's bug
To solve this problem, how can I do it? 
Thank you

**Comment by wu-sheng** [comment]
This could be many reasons. Two kinds of them
1. SkyWalking doesn't make sure the data always there in the storage. Due to your performance limits of OAP and storage cluster deployments, no one can guarantee that. The 1st priority of SkyWalking is keeping your business application safe in memory and network perspective. So, the agent will abandon some traces if your backend(OAP or storage) is not powerful enough. You should be able to see abandon logs in the agents.
1. There are some plugins have bugs, the trace/span are generated, but not finish as expected. Due to that, we call that as `shadow tracing context`, you should be able to find it in the agent log too.

**Comment by huangpang** [comment]
@wu-sheng 
Thank you for your answer
According to your answer, I compared the diary carefully：skywalking-api.log , skywalking-oap-server.log , elasticsearch.log

No exception was found in it. No other information or warning log was found

I summarize the log (about 10 minutes) of the time period when the data is wrong, and I upload it
[skywalking-api-2020031015-16.log](https://github.com/apache/skywalking/files/4316676/skywalking-api-2020031015-16.log)
[skywalking-oap-server202003101516.log](https://github.com/apache/skywalking/files/4316677/skywalking-oap-server202003101516.log)

This problem is a little difficult to track. I don't know if my troubleshooting method is correct

**Comment by wu-sheng** [comment]
Shadow thread is hard to track. The error only shows up randomly.
