### ISSUE TITLE
[Q] I wonder if the GRPC report is compressed？

### ISSUE THREAD

**Issue by dengliming** [apache/skywalking#4554]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I wonder if the GRPC report is compressed？
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What kind of compressed do you mean?

**Comment by wu-sheng** [comment]
Question should go to mail list. 

Mail list: dev@skywalking.apache.org. Mail to dev-subscribe@skywalking.apache.org, follow the reply to subscribe the mail list.

**Comment by dengliming** [comment]
like gzip?

**Comment by wu-sheng** [comment]
Currently no, because from previous HTTP experience, this is a very tricky issue. If gzip is on, the CPU will be burn, and the network load actually wouldn't reduce much. But we haven't tested this in the gRPC case. 

We are welcome you to do the tests and post the result, if the result is positive in some cases, we are welcome to accept the gzip pull request from you.

**Comment by dengliming** [comment]
Got it, Thanks. I will send question by email next time.
