### ISSUE TITLE
More strict PluginTests expected data verifier

### ISSUE THREAD

**Issue by dmsolr** [apache/skywalking#4612]
We found the below fields of reference in `expectedData.yaml` that are not strict enough.  When we work at #4599 .

1. parentTraceSegmentId
2. parentService
3. serviceName

**Comment by wu-sheng** [comment]
> 1.parentTraceSegmentId

Segment id should be fine. Let's keep it not null.

**Comment by kezhenxu94** [comment]
@dmsolr what do you mean by saying "not strict enough"? Any further detail? I have been also planing to verify the E2E expected data more strictly so long, and recently I've got a chance to set up a framework ([yaml-validator](http://github.com/kezhenxu94/yaml-validator)) to do this, and I've been adjusting the E2E tests now, it works well somehow, so please take a look at it to see whether it fits your scenario :) 


P.S. I may need this in my company work so I didn't make it part of the SkyWalking project :)

**Comment by wu-sheng** [comment]
The strict means, we are only using `not null` in the reference validation, but actually, in current protocol we can and should do that.

> P.S. I may need this in my company work so I didn't make it part of the SkyWalking project :)

This is totally understandable, you could choose in/out of ASF for your own. But I need to say, if this tool is a person tool, it is suitable for a TLP to use it directly, because of orphan risk. This principle is not for your project, this is generalized level meaning.

**Comment by dmsolr** [comment]
Hi, @kezhenxu94 
This issue means what the rules of `expectedData.yml` are not strict enough. For instance, `serviceName` should be the exact name, not `not null`.

PS, the project is very awesome. I think we could bring it to the agent-test tools instead of `validator tools`.
