### ISSUE TITLE
can't find the folder of org.apache.skywalking.oap.server.core.register

### ISSUE THREAD

**Issue by coki230** [apache/skywalking#4727]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion

___
### Question
- What do you want to know?
it take me a lot of time to find out why the server aways throws a lot of error which is like this
"ERROR org.apache.skywalking.oap.server.core.remote.client.GRPCRemoteClient$1.onError(GRPCRemoteClient.java:192) - DEADLINE_EXCEEDED: deadline exceeded after 9999968920ns
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED" or "CANCELLED: cancelled before receiving half close"
finnaly i found out that is beacuse the RegisterPersistentWorker save not use bulk mode which cause the big stress of the es. but i cann't find the folder of "org.apache.skywalking.oap.server.core.register" what a wonlderful solution. how can i understand the details?

**Comment by wu-sheng** [comment]
> finnaly i found out that is beacuse the RegisterPersistentWorker save not use bulk mode which cause the big stress of the es. 

Because you can't. That is a sequential operation, using bulk will cause high risk of data inconsistent. Since you understand Chinese, listen to this bi-weekly meeting record, I introduced what is the issue of Register, and why it is removed in 8.0.

https://www.bilibili.com/video/BV1mz411B7To

> but i cann't find the folder of "org.apache.skywalking.oap.server.core.register" 

You must look at the master branch, it has been removed, look at v7.0.0 and v6.6.0 tags, it is there.

**Comment by coki230** [comment]
3Qs a lot.
