### ISSUE TITLE
when use skywalking agent ,arthas is can‘t work well

### ISSUE THREAD

**Issue by RainElohim** [apache/skywalking#4820]
this issue have many detailed informations
https://github.com/alibaba/arthas/issues/1141
please check all comments
thanks

**Comment by wu-sheng** [comment]
I just read that, but, basically, that is not caused by SkyWalking either. 
The *auxiliary$` is generated by byte-buddy automatically, but only once. The instrumentation is controlled by byte-buddy, and we don't do re-transform to any class. 

I don't know why there are so many `com.example.demo.TestController$auxiliary$` created, my guess and assume is, that related to how the Arthas works on the runtime. It keeps creating the new classes on the runtime based on some reason(not sure), and that class triggers the SkyWalking instrumentation again.

**Comment by wu-sheng** [comment]
Ping @candyleer, as you like the agent game :)

**Comment by hengyunabc** [comment]
和Arthas没关系好吧： https://github.com/hengyunabc/skywalking-error-demo

**Comment by wu-sheng** [comment]
English only.

**Comment by wu-sheng** [comment]
Read my reply more carefully. I didn't say it is Arthes fault. In open source, there is no one's fault. I was saying, there is retransfer happening. And that makes the transfer done more than one time.

I am just guessing the Arthes logic, and your demo has just proved my assumption, right?

**Comment by WangJi92** [comment]
It's a little hard to choose, but love Arthas more

**Comment by zhangzhen108** [comment]
@wu-sheng  If other agents do not enhance the class during the first load (transform), the class will be enhanced during the second transform. Then skywalking directly returns the byte stream cached for the first time in the second time, will it overwrite the content enhanced for the second time by other agents? Because the order in which the transform is executed depends on the order in which the Agent is configured.
