### ISSUE TITLE
Low OAP CPU usage

### ISSUE THREAD

**Issue by linliaoy** [apache/skywalking#4931]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
oap 6.6
Low USE of OAP CPU,es thread_tool and FULL GC are normal, and few data in ES, adding multiple OAP node segments will increase a lot of data, and OAP monitoring value TRACe_grpc_v6_in_latency_bucket will increase, SS-LIN view the network port is not congested, it seems there is a bottleneck in OAP at present, but it is not clear which configuration decides, can you analyze it?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I recommend you to analysis the lock and thread status of OAP. Is there too many register happening? Or as seems you are using 6.x or 7.0, is the size of local buffer file increasing?

**Comment by wu-sheng** [comment]
Also, 8.0 has removed the register, and there is no locking mechanism during the processing.
If you can, please try 8.0.0. If this still happens, I think you have to dig more about the status at the OAP codes level. Most users are not facing this.

**Comment by linliaoy** [comment]
![image](https://user-images.githubusercontent.com/16507478/84729566-9ec02780-afc6-11ea-8c80-ae02165d543e.png)
284 threads and 256 connections

**Comment by wu-sheng** [comment]
This is very clear you have register issue. Try 8.0.0, you should be able to avoid this.
But also, at the same time, this register issue means, your endpoints include parameter in it. Eventually, it makes the metrics pointless than usual.

Endpoint including parameter is like, `/prod/123`, `/prod/2344`, `/prod/555`, but actually, it should be `/prod/xxx`. 

This could be caused by many reasons, even just because how you wrote codes. So, besides the upgrade, please take care of this scenario.
