### ISSUE TITLE
It's hard to distinguish business exception and other errors with Error status filter on the trace page

### ISSUE THREAD

**Issue by momo0313** [apache/skywalking#5101]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question

It 's common to use global exception handler in spring. We can throw the all business exceptions in controller, and catch it by a custom ExceptionHandler with ControllerAdvice annotation. 

With the springmvc plugin in agent, it will mark the status of span to error, even though the 200 http status is returned in the global exception handler. In this case, If we choose Error status on the trace page, there are lots of traces with business exception, and it's hard to get more useful errors like 4xx, 5xx and so on.

Is there any good way in this case?

**Comment by wu-sheng** [comment]
> It 's common to use global exception handler in spring. We can throw the all business exceptions in controller, and catch it by a custom ExceptionHandler with ControllerAdvice annotation.

I can't agree it is common or right. Controlling the workflow by exception is rude and low-performance. 
But if you do that, you have to change the source codes on your own. SkyWalking wouldn't take that responsibility because if we do so, we have to check every exception and iterate its parent, it will burn the agent in heavy traffic systems. If you know where to do the filter, change the codes.

**Comment by momo0313** [comment]
@wu-sheng
Is it possible to add a config properties on agent side, such as:  

span.status.check.exclude.exceptions: BusinessException,XXException
span.status.check.include.exceptions: RuntimeException,XXException

If the user want to focus on some custom exceptions, they can get more useful infos by filter Error status of trace.
