### ISSUE TITLE
Inquiry About the Microservice Architecture Employed by `skywalking`

### ISSUE THREAD

**Issue by research-sudo** [apache/skywalking#5117]
I am a researcher investigating the open source projects that are designed by the microservice architectural style (https://martinfowler.com/microservices/). My preliminary investigation shows that the **_skywalking_** project (https://github.com/apache/skywalking) is designed by the microservice architectural style.

Can you please **_confirm_** if my interpretation that this project is designed by following the microservice architectural style is correct? Note that if the projects (e.g., frameworks or tools) support the development of microservices-based systems but themselves are not designed by following the microservice architectural style, please also clarify it?
If my interpretation is correct, what **_features_** or **_characteristics_** of the architecture of this open source project show that the microservice architectural style has been used?
**Optional Question:** Do you know any other open-source projects that are designed by following the microservice architectural style?
I would be greatly appreciative if you can kindly answer the three questions above.

**Comment by wu-sheng** [comment]
SkyWalking is focusing on monitoring the distributed system, w/ container-based, or micro-service based. 

> this project is designed by following the microservice architectural style is correct?

The project provided many extension points, including alarming, dynamic configuration, cluster coordination, storage, alternative transport stack. We are a part of final distributed system. I think your question is not suitable for us. The open-source project is resolving very common problems, such as here APM, and collaborating a lot of people, like us 200+ developers work together, rather than doing as a whole product.
