### ISSUE TITLE
Unary alternative to `TraceSegmentReportService.collect`

### ISSUE THREAD

**Issue by dio** [apache/skywalking#5358]
Why do you submit this issue?

- [x] Feature request

Can we have a unary version of https://github.com/apache/skywalking-data-collect-protocol/blob/b2f381e63702bc43216ef5576637195102302c6e/language-agent/Tracing.proto#L31? Reason is to provide a simpler client-side implementation. An additional supporting argument, see https://buf.build/docs/style-guide/#recommendations at the very end of that section. 

```proto
rpc ReportSegments(ReportSegmentsRequest) returns (ReportSegmentsResponse) {}

message ReportSegmentsRequest {
  repeated SegmentObjects segments = 1;
}

message ReportSegmentResponse {
  Commands commands = 1;   
}
```

cc. @ZackButcher

**Comment by wu-sheng** [comment]
I could add this implement as an option, you want this in the Envoy side? I guess it is more friendly for the resource releasing?

**Comment by wu-sheng** [comment]
@dio Default and recommended in streaming, because it could provide a little better performance, especially when you have a lot of segment(in some agent, 1-2k per stream). So, if this is not a concern at Envoy's side, I could help with this.

**Comment by lizan** [comment]
@dio what's the performance improvement you're looking into for this? You should be able to use current streaming interface as batch (i.e. send gRPC frames in batch), there will be a little of performance penalty to do so.

**Comment by dio** [comment]
This is discussed with @ZackButcher this morning. Probably not only Envoy but other clients. While in Envoy's side it will be simpler in terms of code complexity and in line with other existing tracers.

I think it will not hurt to have alternatives.

**Comment by wu-sheng** [comment]
From the SkyWalking perspective, the side effect is very limited. But envoy should be more sensitive. The bigger the segment collection is, the more memory and network latency will cost. Sending a large set of package is not good, especially in unstable network status.

@lizan @dio I would follow envoy side preference. But the performance issue will be there.

**Comment by lizan** [comment]
Even with the message having repeated, I'd still suggest have stream in RPC signature, just like Envoy ALS does. Unary is just a specialized (N=1) stream. You should be able to use as it is unary.

**Comment by wu-sheng** [comment]
> Even with the message having repeated, I'd still suggest have stream in RPC signature

Yes. From my understanding, when you use `repeated`, the server-side has to begin processing after received the whole collection, rather than streaming to process an entity once it has been received.

**Comment by wu-sheng** [comment]
@dio @ZackButcher Could you confirm whether we still recommend the client side, including envoy, to use the stream mode?

**Comment by dio** [comment]
From an implementation perspective, and the lines of codes involved, I'll be grateful if SkyWalking (for trace data collecting) has a unary interface since I think tracing is a best-effort task.

**Comment by wu-sheng** [comment]
@dio This is very easy on the SkyWalking side. 

But like I and Lizan mentioned, it will cost more memory and CPU on the Envoy side. @lizan Please be sure this is acceptable. That is why I keep confirming the recommendation. I just don't want the SkyWalking's envoy tracing having performance issues.

**Comment by wu-sheng** [comment]
In the 3k op/s envoy, there would be 3k segments, including 6k spans. And in this kind of case, you will have a large list, rather than processing it in a stream mode. This large list will have to waste more memory to cache the data to wait until the whole list sent completed.

**Comment by dio** [comment]
Why would I need to buffer that big? I can always send it right away if I want.

**Comment by wu-sheng** [comment]
I think you will only have one channel and one stub for sending this. 
My understanding, this is no real `one-way` call, as unary, you need to wait for the previous list sent completed. 
My experience is for the agent case, streaming could perform better in a large data set. So, depending on the Envoy team.

**Comment by dio** [comment]
Seems like there is a slight misunderstanding on this. I can always send a set of traces, periodically and the size of the buffer is controlled client-side (e.g. envoy). 

Since this issue is a feature request, I don't expect this to be a blocker or even to be implemented server-side. OTOH, it seems like I can start with https://github.com/apache/skywalking/blob/master/docs/en/protocols/HTTP-API-Protocol.md, sorry that I missed this doc, too lazy to dig. The unary gRPC one will help since it uses HTTP/2.

**Comment by wu-sheng** [comment]
If you want the unary, I will. You don't need to deal with HTTP, and SkyWalking backend has better performance in gRPC than HTTP/1.

My argument is only related to `unary` VS `stream` performance.

@dio I will add this gRPC service in this weekend. I will chase my Tesla tomorrow :)

**Comment by ZackButcher** [comment]
I think there's a little confusion here:
- Primary purpose for this is not performance, but to make the client code easier in Envoy to forward data to skywalking
  - As I understand it, using a stream greatly complicates the code due to Envoy's threading model; @dio and @lizan know better than I how that works
- Like Lizan says, `unary` is just a special case of `stream`
  - `unary` is a `stream` that has exactly 1 message sent and received; `stream` can be `n` message sent `m` message received
  - Because of this, `unary` can have slightly _worse_ performance than `stream` in many/most cases
- Like Sheng says, there is no `one-way` (i.e. "fire and forget") calls in gRPC - `unary` gRPC requires a response (even if the response is empty)
  - This _can_ affect throughput in some cases, depending on how exactly the client and server are pooling threads that handle gRPC requests
  - If SW collector can receive `unary` data, push the request processing to an executor (thread pool), then return a response, you would not see any blocking/queueing on the gRPC stream (though you might see queueing of tasks to be done in your thread pool if agent is outpacing collector). For example, in golang gRPC creates goroutine per `unary` request to avoid this.
  - In general, gRPC avoids head of line blocking (@lizan can keep me honest here)
- Like Dhi points out in the document he links, SW collector use case is not _really_ one that's intended for streaming gRPC (though in practice it performs better, so it makes sense to use it for most agents).

> I think you will only have one channel and one stub for sending this.
> My understanding, this is no real one-way call, as unary, you need to wait for the previous list sent completed.
> My experience is for the agent case, streaming could perform better in a large data set. So, depending on the Envoy team.

I think this is the key confusion - @dio can correct me - but I believe we'd have a stub per Envoy-worker-process, not just a single stub. This is part of what results in the simplification in code on Envoy side. Further, multiple unary RPCs with the same stub won't block each other. gRPC uses H2 multiplexing here; when it comes to literally writing the bytes to the wire, it uses a round-robin strategy across pending requests so that small requests "flow past" large ones. (Again, @lizan please correct me if I got some of the gRPC internals wrong.)

Overall glad to see y'all are fine to add unary - thanks @wu-sheng!

**Comment by wu-sheng** [comment]
Unary definitely works for me, no concern at the SkyWalking side.

@dio Have you separated the trace data into 2 spans?

**Comment by lizan** [comment]
> I think there's a little confusion here:
> 
> * Primary purpose for this is not performance, but to make the client code easier in Envoy to forward data to skywalking
>   
>   * As I understand it, using a stream greatly complicates the code due to Envoy's threading model; @dio and @lizan know better than I how that works

No it doesn't really complicates, that's why I'm saying even if we made that repeated the RPC signature should still be stream, Envoy doesn't use gPRC generated code, and the async client doesn't make specialization for unary. So it is pretty easy to use stream rpc as unary. Just use as it is an unary. 

> * Like Lizan says, `unary` is just a special case of `stream`
>   
>   * `unary` is a `stream` that has exactly 1 message sent and received; `stream` can be `n` messages sent `m` messages received
>   * Because of this, `unary` can have slightly _worse_ performance than `stream` in many/most cases
> * Like Sheng says, there is no `one-way` (i.e. "fire and forget") calls in gRPC - `unary` gRPC requires a response (even if the response is empty)
>   
>   * This _can_ affect throughput in some cases, depending on how exactly the client and server are pooling threads that handle gRPC requests

While gRPC requires a response, it doesn't block the stream, i.e. you don't have to wait any response before sending next batch. The only caveats is H2 flow control, that depends on how server applies that to the stream.

So based on that I don't see a point of adding an unary, it doesn't make performance better or implementation easier.

**Comment by wu-sheng** [comment]
> Envoy doesn't use gPRC generated code, and the async client doesn't make specialization for unary.

@dio Please talk with Lizan. I don't have understood the Envoy codes. :p

**Comment by dio** [comment]
OK. Per my statement, it is a feature request. If we only care about Envoy that is fine per Lizan's comment. I'm thinking it will help the community as well since not everyone likes "streaming".
