### ISSUE TITLE
[CLI]Failed to query JVM instance metrics

### ISSUE THREAD

**Issue by fgksgf** [apache/skywalking#5973]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug

![image](https://user-images.githubusercontent.com/26627380/101460420-8842c980-3974-11eb-9668-22107cf0675b.png)

This bug is detected, because there is no case when metrics' name starts with "instance",  which leads to the scope is `All` instead of `ServiceInstance`.

**Comment by wu-sheng** [comment]
Oh, I don't know there is this kind of logic for query. Could you share why we did this? From my understanding, you only need to set inputs(entity mostly) base on users' input. What is your block?

**Comment by fgksgf** [comment]
> Could you share why we did this? 

Because I want to make it much easier for the user. The scope can be inferred from the metric name without user input. After all, the variety of scopes is limited.

Therefore, there are two types of solutions:
- Add a case
- Let users specify the scope

What do you think?

**Comment by fgksgf** [comment]
> Could you share why we did this? 

Because I want to make it much easier for the user. The scope can be inferred from the metric name without user input. After all, the variety of scopes is limited.

Therefore, there are two types of solutions:
- Add a case
- Let users specify the scope

What do you think?

**Comment by wu-sheng** [comment]
I mean, if the user set `--service` and `--instance`, you know this is expected `instance` scope, right?
If they only give you `--service` with instance metrics name, you could still do this, the OAP would not return error, instead, it returns all `0` data.

**Comment by fgksgf** [comment]
Yes, but there are some special circumstances. For example, this query:
 `swctl metrics top 10 --name="endpoint_cpm" --service=="xxx"`, the user set `--service` but its scope is `Endpoint`. So I think inferring the scope from the metric name is effective.

**Comment by wu-sheng** [comment]
> swctl metrics top 10 --name="endpoint_cpm" --service=="xxx", the user set --service but its scope is Endpoint. So I think inferring the scope from the metric name is effective.

Let's talk about `top n` separately. Have you taken a look at the UI configuration page? There is a `typeOfMetric` query like this, 
https://github.com/apache/skywalking-query-protocol/blob/4be8e459b0ff56ed5d41a3b5c2173ba83668831e/metrics-v2.graphqls#L138
You are using name referencing is very dangerous, and users can't follow, as the OAL script basically could be named by anyone. UI is configurable and not sensitive about this. So, the scope is really necessary in some cases.

![image](https://user-images.githubusercontent.com/5441976/101467527-63068900-397d-11eb-8cc3-9a3b643dd02d.png)

____
About the metrics naming, it is just related to the OAL variable name,
https://github.com/apache/skywalking/blob/4aa9f301d0d97198f023e2d91779222e1a5787dc/oap-server/server-bootstrap/src/main/resources/oal/core.oal#L24
Even we could change it at any minute, we can't afford CLI breaks due to this.

**Comment by fgksgf** [comment]
You are right. Get it. I will let users specify the scope.

**Comment by wu-sheng** [comment]
I think only `top N` requires that, others could follow the auto-scope logic easily
