### ISSUE TITLE
[NodeJS]  Which express version is supported

### ISSUE THREAD

**Issue by WHYSOS** [apache/skywalking#6112]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Which express version is supported

_My version is Express4.13.1;Why can't the request be monitored？Only the requests sent by the server can be monitored.Thanks!_
![image](https://user-images.githubusercontent.com/22768493/103400754-45de6800-4b81-11eb-9ca4-48ded1d2f7b3.png)
![image](https://user-images.githubusercontent.com/22768493/103400865-a077c400-4b81-11eb-97ea-5a5e5bd9dd03.png)

**Comment by kezhenxu94** [comment]
@WHYSOS `express` is built on top of `http`, so even the version 4.13.1 is not supported, the requests should be monitored by `http` plugin, could you share how you use `express`?

**Comment by kezhenxu94** [comment]
@WHYSOS version 4.13.1 is also supported, it turns out to be the same bug of https://github.com/apache/skywalking/issues/6109 , and should be fixed by https://github.com/apache/skywalking-nodejs/pull/20 , hence I'm going to close this and let's track this bug in #6109 , thanks very much for reporting
