### ISSUE TITLE
 SkyWalking doesn't work properly without JavaScript enabled. Please enable it to continue

### ISSUE THREAD

**Issue by lwgo2050** [apache/skywalking#6299]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

I install skywalking 8.3 es, oap.log  skywalking-oap-server.log  webapp-console.log  webapp.log are normal, server started bug when i visit http://localhost:8080 it's always tell me "We're sorry but SkyWalking doesn't work properly without JavaScript enabled. Please enable it to continue." but i check and sure i had enable Javascript.

and console have error like this 
 Uncaught SyntaxError: Unexpected token '<'       app.831aed75.js:1
 Uncaught SyntaxError: Unexpected token '<'   app.831aed75.js:1 
 i guess ui load javascript error ? 

hope to answer, thanks

**Comment by wu-sheng** [comment]
We are setting test env on http://skywalking.apache.org/#demo. You could check there. If there is still this error, you need to check your browser settings.

**Comment by lwgo2050** [comment]
i can open the  url http://skywalking.apache.org/#demo.and the  skywalking ui show correctly,so my browser setting is correct

**Comment by wu-sheng** [comment]
That works then this is the code you are using. Check your local env. We are using trusted domain(apache.org), rather than 127.0.0.1. Still your local env settings.

**Comment by lwgo2050** [comment]
i used also https domain, but i used nginx to foward to the port，Does it matter?

**Comment by Memento1990** [comment]
the SW_OAP_ADDRESS needs **http://** prefix, you may try this.

**Comment by little-hang** [comment]
I got the same problem. I use k8s(not helm) to delpoy sw .
the ui's configmap is as follows:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/24517540/163961970-4086666b-2a96-4968-81b9-0f38c65a7c49.png">
and the oap-server's configmap is as follows:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/24517540/163962322-a029f2c2-8104-4a97-bdca-4c52bc854b32.png">
 and then i verify the oap-server port,it's ok:
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/24517540/163962703-6aa3799b-d207-41cf-b691-ab8d04dee692.png">


the problem is:
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/24517540/163962893-7288a8c5-ebe3-4288-893e-b16848749147.png">

**Comment by Benxiaojia-Daniel-Li** [comment]
> the SW_OAP_ADDRESS needs **http://** prefix, you may try this.

thank you ,  I have solved this problem  following your reply ，appreciate ！
