### ISSUE TITLE
SkyWalking OAP version reporter through CDS

### ISSUE THREAD

**Issue by Shikugawa** [apache/skywalking#6571]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

### Requirement or improvement

I think that CDS feature can be utilized reporting OAP version to agent. It can be required to switch version-specific behavior on the agent. WDYT?

**Comment by wu-sheng** [comment]
Report OAP agent? Could you provide a little more details about how it helps? And how the agent will use it if there is a version.

**Comment by Shikugawa** [comment]
@wu-sheng This is just my consideration based on imagination. If we have a breaking endpoint change of data collect protocol, an agent will want to switch them. Do we have these situations?

**Comment by wu-sheng** [comment]
> @wu-sheng This is just my consideration based on imagination. If we have a breaking endpoint change of data collect protocol, an agent will want to switch them. Do we have these situations?

2 background stories are, SkyWalking as a tracer server, our ecosystem is set up very slowly. So, the protocol is nearly never changed. v3(we are using) is set up in 2020, v2 was in 2017.
Even, we need to change something, we expect to add a new field, rather than a break.
At last, we have to, we will change service name(v2->v3), or like you asked us to add `v3` in the namespace. So you could check GRPC's `unimplemented service` error.

**Comment by Shikugawa** [comment]
Sure. maybe we don't have this right now.

**Comment by wu-sheng** [comment]
I am going to close this discussion for now. Let's see whether there is a new case.
