### ISSUE TITLE
The reason to use  "wait until " refresh policy

### ISSUE THREAD

**Issue by 3838438abcd** [apache/skywalking#6573]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
1.The Storge type I use is ES, I found the sync bulk refresh policy is "WriteRequest.RefreshPolicy.WAIT_UNTIL" which must wait before ES complete the action of refresh ，wehter it influence the perfance of oap-server? 
2.There is a configuration named "flushInterval" which will incluence the refresh interval of ES and async bulk, it will increase the inverval of async bulk, but I think exist conflict with sync bulk, sync bulk action must wait refresh interval , it will be more easy timeout when increase the "flushInterval"
___
### Bug
- Which version of SkyWalking, OS, and JRE?
skywalking 8.1.0, centos7.6, storage type is ES7
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
(1) After you read the source codes, you will notice, there is a combination/merge operation between memory and database. If read the dirty data in the next round, the update would not be accurate. Performance is a thing having a lower priority than accuracy. Otherwise, there is pointless.
(2) I don't agree with you. `refresh_interval` only relates to the record-type data, mostly traces, and logs. (1) is about metrics.
