### ISSUE TITLE
getAllService() return duplicated service

### ISSUE THREAD

**Issue by xuanyu66** [apache/skywalking#6598]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

We found getAllService() return duplicated service?
I want to know how skywalking Guarantee ES has unique ServiceTraffic Data.
getAllService() will query All index which has prefix "service_traffic".

**Comment by wu-sheng** [comment]
Please search before submitting a new issue.

**Comment by xuanyu66** [comment]
I searched duplicated service, only found #1124.

**Comment by wu-sheng** [comment]
The simple version is, OAP query the storage first, if not found, it inserts a new one. If somehow ES server is not fully functional, such as a shard is not working, you will face this case.
We could simply do `distinct` in the OAP query and pretend this never happens, but considering the reality, we don't. Because when you see this, it means your ES server is not working well as you thought, some metrics are not accurate too.
