### ISSUE TITLE
[NODEJS] This dependency was not found: async_hooks

### ISSUE THREAD

**Issue by githubphy** [apache/skywalking#6637]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
This dependency was not found: async_ Hooks, but npm install -- save async_hooks is already installed
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
@githubphy make sure you use Node version >=10

**Comment by kezhenxu94** [comment]
Also, provide more details when asking questions

**Comment by githubphy** [comment]
> Also, provide more details when asking questions

One of my applications uses skywalking-backend-js. An error occurs when compiling this application. The error message is as shown in the figure. I use Node version is v15.5.0
![image](https://user-images.githubusercontent.com/9158859/112790457-f3361e80-9091-11eb-886a-579fa80520fa.png)

**Comment by kezhenxu94** [comment]
The async_hooks module has been part of core since Node.js version 8. Could it be that your environment somehow loads an old version of Node.js even though you have a newer version installed?

If you in your code try to run console.log('Running Node.js version:', process.version), does it still output version 10?

Are you trying to use it with webpack? That looks like the error you get when trying to bundle Node.js code that uses non-browser-compatible code without explicitly telling webpack to allow it. See: https://webpack.js.org/configuration/node#other-node-core-libraries
