### ISSUE TITLE
skywalking 8.5.0 collector.backend_service can multiple IPs be configured to support load balancing?

### ISSUE THREAD

**Issue by netfreeperson** [apache/skywalking#6847]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
skywalking 8.5.0 collector.backend_service can multiple IPs be configured to support load balancing?

**Comment by wu-sheng** [comment]
I think https://github.com/apache/skywalking/issues/6844 is very clear. Why are you keeping asking?

**Comment by netfreeperson** [comment]
> I think #6844 is very clear. Why are you keeping asking?

1、because i think config multiple IPs may only support cluster failover mechanism but not support load balancing. 

2、Also, since OAP backen supports a central registry cluster（like nacos）, can the Agent client get the list of services directly from the registry

3、Also I wonder why the server information of log collection connection needs to be configured separately?Is it to be separate from trace and metric collection?

thanks

**Comment by wu-sheng** [comment]
> 1、because i think config multiple IPs may only support cluster failover mechanism but not support load balancing.

I explained to you, why this is not required.

> 2、Also, since OAP backen supports a central registry cluster（like nacos）, can the Agent client get the list of services directly from the registry

Because agent and backend typically are not in one VPC, even region. Things like Nacos is pointless. And with today's k8s DNS driven and service mesh, implementing this client-side service discovery is a really old fashion thing. OAP could work with many register central, agent can't and shouldn't work with all options.

> 3、Also I wonder why the server information of log collection connection needs to be configured separately?Is it to be separate from trace and metric collection?

Because logs could be collected by other agents, fluentd, filebeat, etc. The thing you are seeing today on the release is just a very small piece of SkyWalking's landscape. So it is being defined as a plugin and reporter only.
SkyWalking project is expanding in the last 5 years, many things are upgrading.
