### ISSUE TITLE
how to config agent in nacos

### ISSUE THREAD

**Issue by netfreeperson** [apache/skywalking#6854]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?
how to config agent in nacos? 
I can't do either of the two methods shown below.
![agent_config_1](https://user-images.githubusercontent.com/10592599/116222023-c3596400-a780-11eb-9cef-bca1a6d93d28.jpg)
![agent_config_2](https://user-images.githubusercontent.com/10592599/116222029-c48a9100-a780-11eb-948e-6cb47c584ff1.jpg)

**Comment by wu-sheng** [comment]
You don't understand the document correctly. All dynamic configuration is one key with a YAML formatted file. Read the documentation more carefully, rather than keeping submitting issues. 
The community has very limited resources and bandwidth to answer questions, if you keep doing this, you are wasting the resources to resolve something you could resolve by yourself.
I would not put much time as before to reply to you again, once your question begins more reasonably.

**Comment by netfreeperson** [comment]
> You don't understand the document correctly. All dynamic configuration is one key with a YAML formatted file. Read the documentation more carefully, rather than keeping submitting issues.
> The community has very limited resources and bandwidth to answer questions, if you keep doing this, you are wasting the resources to resolve something you could resolve by yourself.
> I would not put much time as before to reply to you again, once your question begins more reasonably.

thanks a lot for your answer!
But I think the documentation could be a little more detailed.
I asked this question after going through the documentation and looking up as much information as I could.
Finally, by looking at the source code, I know that this configuration item（configuration-discovery.default.agentConfigurations） needs to be configured in nacos/CDS.
thanks!!!

**Comment by wu-sheng** [comment]
Document is from people of community, including youself. If no one takes an action, from community understanding, the document is good enough.
This is not product specification. We need actions, asking is easy.
