### ISSUE TITLE
Allow multiple definitions as fallback in `metadata-service-mapping.yaml` file

### ISSUE THREAD

**Issue by sergicastro** [apache/skywalking#6901]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

### Requirement or improvement

Regarding the [metadata-service-mapping.yaml](https://github.com/apache/skywalking/blob/master/oap-server/server-bootstrap/src/main/resources/metadata-service-mapping.yaml) file used to configure which fields/labels are used to extract required data, would be nice to provide a way to configure multiple values treated as a fallback mechanism to extract the required data.

For example, let's say I want to extract the service name from the label `service.istio.io/canonical-name` but I want to fall back into `app.kubernetes.io/name` or `app` labels if the first one is not defined.
Allowing a comma-separated value in the config file would be enough to what needs to be processed to find the service name in this case.
The config file would look like this:
```yaml
serviceName: ${LABELS."service.istio.io/canonical-name"},${LABELS."app.kubernetes.io/name"},${LABELS."app"}
serviceInstanceName: ${NAME}
```

This is just a suggestion, any other implementation covering the requirement is welcome.

**Comment by kezhenxu94** [comment]
> The config file would look like this:
> 
> ```yaml
> serviceName: ${LABELS."service.istio.io/canonical-name"},${LABELS."app.kubernetes.io/name"},${LABELS."app"}
> serviceInstanceName: ${NAME}
> ```
> 
> This is just a suggestion, any other implementation covering the requirement is welcome.

Instead of `${a},${b},${c}`, I used `${a,b,c}` in #6933 , so something like `prefix::${a,b,c}::suffix` will work if `a` is empty but `b` is not (say `test`), it evaluates as `prefix::test::suffix`, using `${a},${b},${c}` will need to duplicate the prefixes and suffixes like `prefix::${a}::suffix`, `prefix::${b}::suffix`, `prefix::${c}::suffix`, and the empty check is even complicated since `a == null` evaluates `prefix::${a}::suffix` as `prefix::null::suffix`
