### ISSUE TITLE
Switch to JRE base image from JDK

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#7597]
I think we should do this for dev images and official release. @hanahmily 

@kezhenxu94 I think we should update agent's base image, right?

**Comment by hanahmily** [comment]
Once we select `jre` image, we have to install OpenSSL to support `TLS`.

**Comment by wu-sheng** [comment]
I know. But we should and lock the version to avoid unexpected change over time.

**Comment by hanahmily** [comment]
> I know. But we should and lock the version to avoid unexpected change over time.

Do you mean we should opt for a tag with the minor version, for example, `jdk-11.0.12_7-alpine`? I agree with that.

But this strategy doesn't work regarding CVEs from underlying OS, a nightly build and push strategy can help us to fix it. Once the base image pushes a patch to fix some issues, we can fix it through rebuild and repush. 

This strategy only works for dev images because release images should be pushed by hand. That means we have to update them manually and perioidyly.

**Comment by wu-sheng** [comment]
Yes, changing binary codes(including OS level files) with time would be a very challenging work, I am afraid.

**Comment by wu-sheng** [comment]
Dev version is fine, because basically, we have image per commit id. It would be automatically fix in the name dev version.

**Comment by wu-sheng** [comment]
@hanahmily `JDK->JRE` is not about CVE case, it is a just common way for a release image. Because we are not going to compile anything in the runtime, then JDK is not required.

**Comment by hanahmily** [comment]
> `JDK->JRE` is not about CVE case, it is a just common way for a release image. Because we are not going to compile anything in the runtime, then JDK is not required.

Why I mentioned the CVE case here intends to explain that even we select a specific `JRE`, it can't lock the underlying OS. A more common way to rebuild and re-push released images periodically. But Apache foundation projects can't follow this strategy easily unless they belong to official images, like tomcat.

**Comment by wu-sheng** [comment]
Yes, I know. This is not a case we can't fix, right?
