### ISSUE TITLE
[Bug] KafkaLogHandler cannot recognize namespace

### ISSUE THREAD

**Issue by dmsolr** [apache/skywalking#7706]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

The base question is why KafkaLogHandler does not inherit from AbstractKafkaHandler from the student @codeglzhang from Summer 2021. There is some common function in the AbstractKakaHandler, such as to get an actual topic name.

### What you expected to happen

The topic name includes namespace when the user has setten namespace.

### How to reproduce

none

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dmsolr** [comment]
@codeglzhang Could you fix it

**Comment by codeglzhang** [comment]
No problem.



Ganglin Zhang



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 14, 2021 11:25 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/skywalking] [Bug] KafkaLogHandler cannot recognize namespace (#7706)




 
@codeglzhang Could you fix it
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wu-sheng** [comment]
We are close to 8.8.0 release, please fix this as soon as possible.
Thanks.

**Comment by codeglzhang** [comment]
OK, I'll fix it tomorrow.



---Original---
From: "吴晟 Wu ***@***.***&gt;
Date: Tue, Sep 14, 2021 14:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/skywalking] [Bug] KafkaLogHandler cannot recognize namespace (#7706)




 
We are close to 8.8.0 release, please fix this as soon as possible.
 Thanks.
 
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
