### ISSUE TITLE
Grouping the performance matrix per application instead per VM

### ISSUE THREAD

**Issue by zone1511** [apache/skywalking#788]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Is it possible to let the agent return per application's performance matrix instead per VM? For example I have J2ee container and multiple application has been deployed.

**Comment by wu-sheng** [comment]
@zone1511 I think that will be hard, because of following reasons:
1. JVM/server metrics are only related to VM, Sorry.
1. Application topology map based on this application, instead of VM-level application, will make people hard to understand, and more complex. Also, we are facing to move Docker based arch, right? It is not popular to deploy more than one application in a container, even not popular in Cloud or VM based env.
1. This requirement ask a change to our core, in order to allow two application context existed.
1. We need to rename application to config + `/webroot`, causes more config for end users.

So, in technical way, it is possible. But I would say easy.

Do you think it is worth to do so?

**Comment by zone1511** [comment]
One challenge I can think of is how to identify two figure comes from two application. For j2ee. Class loader is a good way to identify but if the class is loaded from parent class loader then it is complicated. Anyway. Just brain storm the possibility.

**Comment by wu-sheng** [comment]
> One challenge I can think of is how to identify two figure comes from two application. For j2ee. Class loader is a good way to identify but if the class is loaded from parent class loader then it is complicated. Anyway. Just brain storm the possibility.

I think you didn't need this complex way to identify the web application. You can use the web-root detection to find out the application's web root path. Then, when you have a transaction, you can know the application based the url prefix.
