### ISSUE TITLE
[Feature] [BanyanDB] Replication mechanism inside cluster.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#8501]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

BanyanDB should support a replication mechanism for making the server more stable and optimization for queries.
This replication only happens inside the cluster, with high network quality(high speed and low latency). In this case, replication latency should be low.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanahmily** [comment]
The latency is unstable even in high network quality. The [fallacies](https://en.wikipedia.org/wiki/Fallacies_of_distributed_computing) of distributed computing told us the network is always unreliable. So we should assume the latency will/must be inevitable. The replication of banyandb should introduce the consistency model to handle the latency, bandwidth, and other network issues.

Cassandra first introduces tune consistency to determine which consistency level they need. But I prefer the M3DB's [simplified version](https://m3db.io/docs/architecture/m3db/consistencylevels/#:~:text=M3DB%20provides%20variable%20consistency%20levels,handled%20at%20the%20client%20level.)  

Since the liaison is the gateway of the master and replicas, the consistency strategy could be its responsibility.
