### ISSUE TITLE
[Python] The local log error stack is truncated

### ISSUE THREAD

**Issue by wzy960520** [apache/skywalking#8699]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Python Agent (apache/skywalking-python)

### What happened

When reporting to the server, I can understand that the error stack printed to the log is truncated, but the error stack recorded to the local log is truncated, so the specific error cannot be located

### What you expected to happen

The error stack recorded to the local log is not truncated and the error can be located smoothly

### How to reproduce

An error with an error stack depth greater than 5 occurred, and the log on the server was truncated, as was the local log

### Anything else

Every time

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you going to propose some changes?

**Comment by wzy960520** [comment]
> Are you going to propose some changes?



> Are you going to propose some changes?

https://github.com/apache/skywalking-python/pull/190

**Comment by dipadipa** [comment]
this occurs to me too, 
skywalking save backtrace depth of 5 with default, this constrait take effect to standard logging module either.

**Comment by Superskyyy** [comment]
Thanks for the pull request! But on second thought, the solution provided in the PR look a bit off to me. 

To my understanding, the problem occurs due to the existence of a cached `exc_text` attribute contained inside the `LogRecord` object which `sw_logging.transform()` set during the interception.  

The following is from the Python logging module, as we can see the cache is done by this chunk of code. The bug occurs because SkyWalking agent did not clear the cache after doing the formatting, therefore, other formatters would just reuse the cached exception, essentially bypassing the arguments.
```
    if record.exc_info:
        # Cache the traceback text to avoid converting it multiple times
        # (it's constant anyway)
        if not record.exc_text:
            record.exc_text = self.formatException(record.exc_info)
```
Now, if we simply switch the lines around by executing the user's handler first and then format by SkyWalking agent, it seems to me that it would cause the same issue (but reversed - UI shows whatever exception format that user handler.formatter uses). 

I will send another PR to address the issue.

**Comment by wu-sheng** [comment]
@Superskyyy Would you send a pull request soon? So should I revert https://github.com/apache/skywalking-python/pull/190?

**Comment by Superskyyy** [comment]
> @Superskyyy Would you send a pull request soon? So should I revert https://github.com/apache/skywalking-python/pull/190?

Yes sir I will PR later today. Please revert it for clarity.
