### ISSUE TITLE
[Feature] endpoint name drop-down box to the limit

### ISSUE THREAD

**Issue by andotorg** [apache/skywalking#9077]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

```
export const Endpoints = {
variable: '$serviceId: ID!, $keyword: String!',
query: getEndpoints: searchEndpoint(serviceId: $serviceId, keyword: $keyword, limit: 100) { key: id label: name },
};
```
Because skywalking has access to many systems and there are many endpoints, it is obviously inappropriate to add the data of the drop-down box to the limit

### Use case

recovery input endpoint name  the request path

### Related issues

not

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Endpoint search would not pull all data, that is unrealistic.

**Comment by andotorg** [comment]
What's the point of endpoint name search? There is no reference meaning. I think it is better to replace the input box before 8.6 instead of the drop-down selection box. That's what I mean

**Comment by andotorg** [comment]
I think we can open this question and think about it

**Comment by andotorg** [comment]
When the user inputs, the server will fuzzy query the latest data return according to the user input, which is the best user experience

**Comment by wu-sheng** [comment]
There was a long discussion one year ago, this search is simple but has a super bad performance impact on the trace query. So, the community has decided to remove it.
This is a community, diverse groups of people, make the final decision. If you want your voice to be considered seriously, you need to be a part of the committer team based on your contributions to this community. 
A project can't make everyone happy

**Comment by andotorg** [comment]
please， How to be part of the submitter team.

**Comment by andotorg** [comment]
I hope to submit the corresponding code to contribute to this community

**Comment by wu-sheng** [comment]
There is no `submitter team` in the ASF.
The committer team is the one is trusted by the PMC(Project Management Committee), who could do routine code review and merging. The PMC is a smaller group of people watching and sheepherders of the project. 

This doc would show how a committer gets promoted, https://skywalking.apache.org/docs/main/latest/en/guides/asf/committer/, and here are the current committers and PMC members, https://skywalking.apache.org/team/.

The basic principle is, that you need to begin contributing to the project through pull requests, such as bug fixing, or begin to work on a new feature if you have an idea, the idea gets discussed, and at least one of PMC gets you to support to do.

SkyWalking is a community of volunteers, so, there is no one to assign you anything, you need to find things to do because you feel you want to.

About this feature(endpoint name-based search), the conclusion was made, that unless we have committers to initial a new discussion again, we wouldn't accept it back in the mainstream. This is how a community works, we have 600+ code contributors, and countless users. The decision is the decision, very serious, not be able to change randomly.

**Comment by andotorg** [comment]
I see. Thank you for your answer。

**Comment by andotorg** [comment]
skywalking 8.7.0 have a webui bug, submene  "xxx.com:8080/trace" refresh page，It will jump to the back-end 404 address
<img width="597" alt="image" src="https://user-images.githubusercontent.com/25116294/168937666-820a8e24-d5bb-4240-ae8d-953e30ea4a5d.png">

**Comment by andotorg** [comment]
> skywalking 8.7.0 have a webui bug, submene "xxx.com:8080/trace" refresh page，It will jump to the back-end 404 address <img alt="image" width="597" src="https://user-images.githubusercontent.com/25116294/168937666-820a8e24-d5bb-4240-ae8d-953e30ea4a5d.png">

After my testing of each version, only 8.7 will have this problem, and neither 8.6 nor 8.8 will

**Comment by wu-sheng** [comment]
Now, we are working on 9.1, the old versions are not our concern.

**Comment by andotorg** [comment]
There are no plans to use versions above 9.0

**Comment by andotorg** [comment]
ok, Thanks
