### ISSUE TITLE
[Feature] Enhance etcd auth configuration

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9187]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Embed etcd keeps complaining: 

```
simple token is not cryptographically signed
```

which might relate to its [v3 auth design](https://etcd.io/docs/v3.2/learning/auth_design/#two-types-of-tokens-simple-and-jwt). The solution is to pick up the JWT token which is cryptographically signed. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pg-yang** [comment]
I'm afraid I can't understand this issue .
To use JWT, etct-server should add flag `--auth-token=jwt` to start command line. etcd-client needn't do anything

**Comment by hanahmily** [comment]
The related configuration is https://etcd.io/docs/v3.2/op-guide/configuration/#--auth-token

**Comment by rabajaj0509** [comment]
Which repository will these changes be required in?

**Comment by wu-sheng** [comment]
skywalking-banyandb

**Comment by rabajaj0509** [comment]
From the documentation provided for etcd v3 auth design, it seems that there is no mention of refresh tokens in etcd. In this case, the user might have to re-authenticate each time the token expires, meaning if API is called using a script with a time interval, then the user might need to re-authenticate and the script would be stopped since the token expired.  @hanahmily do you know if implementing refresh tokens is possible in this case or if there is no need for it?

**Comment by hanahmily** [comment]
FWIK, Etcd's JWT token is "stateless", being never stored in any storage. Refreshing/Renewing such a token is not necessary. For example, k0s creates a token during booting, https://github.com/k0sproject/k0s/blob/main/pkg/component/controller/etcd.go#L194, never renewing it. 

But the key/cert pair should have a chance to get renewed. Users could leverage [vault](https://www.vaultproject.io/) or other tools to generate a new key/cert pair which the BanyanDB server can load to create new tokens.
