### ISSUE TITLE
[Bug] [PHP] Bugs on Reporter (channel/worker).

### ISSUE THREAD

**Issue by jmjoy** [apache/skywalking#9831]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

PHP (apache/skywalking-php)

### What happened

As discussed there (https://github.com/apache/skywalking-php/pull/24), non-blocking stream fails on write_all occasionally (https://github.com/apache/skywalking-php/pull/24#discussion_r1000112320).

Now @phanalpha temporarily set the sender blocking to pass the CI, but this will cause the PHP worker process to block when the uds buffer is full or the grpc process exits unexpectedly.

Therefore, we need to choose another non blocking sender mode to replace the existing one.

### What you expected to happen

Non blocking sender and reliable.

### How to reproduce

Set sender nonblocking to true.

https://github.com/phanalpha/skywalking-php/blob/357cda037306bfb5c2cff41b162dacd6543145f4/src/channel.rs#L36

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jmjoy** [comment]
My current idea is to use `UnixDatagram` instead of `UnixStream`.

 As the document (https://man7.org/linux/man-pages/man7/unix.7.html) says:

> SOCK_DGRAM, for a datagram-oriented
>        socket that preserves message boundaries (as on most UNIX
>        implementations, UNIX domain datagram sockets are always reliable
>        and don't reorder datagrams)

But also have to solve the problem in mentioned in https://github.com/apache/skywalking-php/pull/15 for MacOS.

**Comment by phanalpha** [comment]
I've made a mistake (before). After digging into the code, I think the problem is not about `Datagram` or `Stream`. A 'pipe' is used as an mpsc channel for now. The actual problem is multi-process concurrent writing to the same pipe. A `Mutex` has no help with that or it would cause performance impact. IMHO, we may need to switch to `UnixListener` and I'm working on it.

**Comment by jmjoy** [comment]
Indeed, in the case of large concurrency, multiple fpm worker processes or multiple swoole coroutines write data to the sender at the same time.

I think the solution is to use UnixDatagram which can determine the data boundary, carry the requested ID on the data packet, and then reassemble it at the receiver.

**Comment by phanalpha** [comment]
There are two problems here: one is concurrent writing, and the other is blocking. `UnixDatagram` may solve the concurrent writing problem. Since we could not be sure that all data fit one write, we must multiplex the stream manually which could be tricky. On the other hand, busy writing to a non-blocking stream without retries almost always causes problems. IMHO, `UnixListener` and per fpm (side) threads solve each.

**Comment by wu-sheng** [comment]
Is this fixed?

**Comment by phanalpha** [comment]
I think we have fixed it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
